config/routes.rb
Rails.application.routes.draw do

  root 'root#index'

  get 'reset' => 'root#reset', as: :reset

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def index
    value = CGI.escape("Cookies are working " + Time.now.utc.to_s)
    response.headers["Set-Cookie"] = "cookie-test=%s; Path=/; Secure; HttpOnly" % value
  end

  def reset
    cookies.clear
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookie Test</title>
  <%# stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%# javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/root/index.html.erb
<h1>Links</h1>
<ul>
  <li><a href="http://cookie.revolt.org">http://cookie.revolt.org</a></li>
  <li><a href="https://cookie.revolt.org">https://cookie.revolt.org</a></li>
  <li><a href="http://it2fobyhmgfjdplqurjzm2eme35v4xjlzr6k2wxj4va2amq7yeda5tid.onion">http://it2fobyhmgfjdplqurjzm2eme35v4xjlzr6k2wxj4va2amq7yeda5tid.onion</a></li>
</ul>

<h1>Cookie test</h1>

<pre style="background: #eee; padding: 20px">
  <%= cookies['cookie-test'] || 'no cookie value set, refresh the page' %>
</pre>

<a href="<%= reset_path %>">reset cookies</a>